// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG6SZVQyaDBcjq3fFd9_QdLzDBFBsKVgs',
    appId: '1:497150539716:web:1b6ffcad2d0792d8731691',
    messagingSenderId: '497150539716',
    projectId: 'ai-chat-app-shodiyor',
    authDomain: 'ai-chat-app-shodiyor.firebaseapp.com',
    storageBucket: 'ai-chat-app-shodiyor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN1rWaMsWTAVurSbsPA43aM6AoG7WsyPA',
    appId: '1:497150539716:android:f6f07bd0fe8f5cbc731691',
    messagingSenderId: '497150539716',
    projectId: 'ai-chat-app-shodiyor',
    storageBucket: 'ai-chat-app-shodiyor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE64cypGq97uyeF_tQ0TSvLO6kIj5A3bk',
    appId: '1:497150539716:ios:57ca4ca6ff60a828731691',
    messagingSenderId: '497150539716',
    projectId: 'ai-chat-app-shodiyor',
    storageBucket: 'ai-chat-app-shodiyor.firebasestorage.app',
    iosClientId: '497150539716-5dle8780q17po775sd50pq7es9k8ang2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE64cypGq97uyeF_tQ0TSvLO6kIj5A3bk',
    appId: '1:497150539716:ios:4695cbc5802466c7731691',
    messagingSenderId: '497150539716',
    projectId: 'ai-chat-app-shodiyor',
    storageBucket: 'ai-chat-app-shodiyor.firebasestorage.app',
    iosClientId: '497150539716-ovmm5dqktom3ofr8a6jp60l985j0fk3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG6SZVQyaDBcjq3fFd9_QdLzDBFBsKVgs',
    appId: '1:497150539716:web:a172330b21a0d575731691',
    messagingSenderId: '497150539716',
    projectId: 'ai-chat-app-shodiyor',
    authDomain: 'ai-chat-app-shodiyor.firebaseapp.com',
    storageBucket: 'ai-chat-app-shodiyor.firebasestorage.app',
  );
}
